std::complex<double> airy_ai(std::complex<double> z);
std::complex<double> airy_ai_diff(std::complex<double> z);
std::complex<double> airy_ai_scal(std::complex<double> z);
std::complex<double> airy_ai_diff_scal(std::complex<double> z);
std::complex<double> airy_bi(std::complex<double> z);
std::complex<double> airy_bi_diff(std::complex<double> z);
std::complex<double> airy_bi_scal(std::complex<double> z);
std::complex<double> airy_bi_diff_scal(std::complex<double> z);
std::complex<double> cyl_h1(double nu, std::complex<double> z);
std::complex<double> cyl_h1_scal(double nu, std::complex<double> z);
void cyl_h1_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_h1_arr);
void cyl_h1_scal_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_h2_scal_arr);
std::complex<double> cyl_h2(double nu, std::complex<double> z);
std::complex<double> cyl_h2_scal(double nu, std::complex<double> z);
void cyl_h2_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_h1_arr);
void cyl_h2_scal_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_h2_scal_arr);
std::complex<double> cyl_i(double nu, std::complex<double> z);
std::complex<double> cyl_i_scal(double nu, std::complex<double> z);
void cyl_i_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_i_arr);
void cyl_i_scal_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_i_scal_arr);
std::complex<double> cyl_j(double nu, std::complex<double> z);
std::complex<double> cyl_j_scal(double nu, std::complex<double> z);
void cyl_j_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_i_arr);
void cyl_j_scal_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_i_scal_arr);
std::complex<double> cyl_k(double nu, std::complex<double> z);
std::complex<double> cyl_k_scal(double nu, std::complex<double> z);
void cyl_k_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_i_arr);
void cyl_k_scal_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_i_scal_arr);
std::complex<double> cyl_y(double nu, std::complex<double> z);
std::complex<double> cyl_y_scal(double nu, std::complex<double> z);
void cyl_y_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_i_arr);
void cyl_y_scal_seq(double nu, int n, std::complex<double> z, std::complex<double> *cyl_i_scal_arr);