double complex airy_ai(double complex z);
double complex airy_ai_diff(double complex z);
double complex airy_ai_scal(double complex z);
double complex airy_ai_diff_scal(double complex z);
double complex airy_bi(double complex z);
double complex airy_bi_diff(double complex z);
double complex airy_bi_scal(double complex z);
double complex airy_bi_diff_scal(double complex z);
double complex cyl_h1(double nu, double complex z);
double complex cyl_h1_scal(double nu, double complex z);
void cyl_h1_seq(double nu, int n, double complex z, double complex *cyl_h1_arr);
void cyl_h1_scal_seq(double nu, int n, double complex z, double complex *cyl_h2_scal_arr);
double complex cyl_h2(double nu, double complex z);
double complex cyl_h2_scal(double nu, double complex z);
void cyl_h2_seq(double nu, int n, double complex z, double complex *cyl_h1_arr);
void cyl_h2_scal_seq(double nu, int n, double complex z, double complex *cyl_h2_scal_arr);
double complex cyl_i(double nu, double complex z);
double complex cyl_i_scal(double nu, double complex z);
void cyl_i_seq(double nu, int n, double complex z, double complex *cyl_i_arr);
void cyl_i_scal_seq(double nu, int n, double complex z, double complex *cyl_i_scal_arr);
double complex cyl_j(double nu, double complex z);
double complex cyl_j_scal(double nu, double complex z);
void cyl_j_seq(double nu, int n, double complex z, double complex *cyl_i_arr);
void cyl_j_scal_seq(double nu, int n, double complex z, double complex *cyl_i_scal_arr);
double complex cyl_k(double nu, double complex z);
double complex cyl_k_scal(double nu, double complex z);
void cyl_k_seq(double nu, int n, double complex z, double complex *cyl_i_arr);
void cyl_k_scal_seq(double nu, int n, double complex z, double complex *cyl_i_scal_arr);
double complex cyl_y(double nu, double complex z);
double complex cyl_y_scal(double nu, double complex z);
void cyl_y_seq(double nu, int n, double complex z, double complex *cyl_i_arr);
void cyl_y_scal_seq(double nu, int n, double complex z, double complex *cyl_i_scal_arr);